// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: server/proto/api.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KDFParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Time          uint32                 `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`
	MemKib        uint32                 `protobuf:"varint,2,opt,name=mem_kib,json=memKib,proto3" json:"mem_kib,omitempty"`
	Par           uint32                 `protobuf:"varint,3,opt,name=par,proto3" json:"par,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KDFParams) Reset() {
	*x = KDFParams{}
	mi := &file_server_proto_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KDFParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KDFParams) ProtoMessage() {}

func (x *KDFParams) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KDFParams.ProtoReflect.Descriptor instead.
func (*KDFParams) Descriptor() ([]byte, []int) {
	return file_server_proto_api_proto_rawDescGZIP(), []int{0}
}

func (x *KDFParams) GetTime() uint32 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *KDFParams) GetMemKib() uint32 {
	if x != nil {
		return x.MemKib
	}
	return 0
}

func (x *KDFParams) GetPar() uint32 {
	if x != nil {
		return x.Par
	}
	return 0
}

type RegStart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegStart) Reset() {
	*x = RegStart{}
	mi := &file_server_proto_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegStart) ProtoMessage() {}

func (x *RegStart) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegStart.ProtoReflect.Descriptor instead.
func (*RegStart) Descriptor() ([]byte, []int) {
	return file_server_proto_api_proto_rawDescGZIP(), []int{1}
}

func (x *RegStart) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

type RegParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KdfParams     *KDFParams             `protobuf:"bytes,1,opt,name=kdf_params,json=kdfParams,proto3" json:"kdf_params,omitempty"`
	SaltRoot      []byte                 `protobuf:"bytes,2,opt,name=salt_root,json=saltRoot,proto3" json:"salt_root,omitempty"`
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegParams) Reset() {
	*x = RegParams{}
	mi := &file_server_proto_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegParams) ProtoMessage() {}

func (x *RegParams) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegParams.ProtoReflect.Descriptor instead.
func (*RegParams) Descriptor() ([]byte, []int) {
	return file_server_proto_api_proto_rawDescGZIP(), []int{2}
}

func (x *RegParams) GetKdfParams() *KDFParams {
	if x != nil {
		return x.KdfParams
	}
	return nil
}

func (x *RegParams) GetSaltRoot() []byte {
	if x != nil {
		return x.SaltRoot
	}
	return nil
}

func (x *RegParams) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type RegComplete struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Login         string                 `protobuf:"bytes,2,opt,name=login,proto3" json:"login,omitempty"`
	SaltRoot      []byte                 `protobuf:"bytes,3,opt,name=salt_root,json=saltRoot,proto3" json:"salt_root,omitempty"`
	KdfParams     *KDFParams             `protobuf:"bytes,4,opt,name=kdf_params,json=kdfParams,proto3" json:"kdf_params,omitempty"`
	StoredKey     []byte                 `protobuf:"bytes,5,opt,name=stored_key,json=storedKey,proto3" json:"stored_key,omitempty"`
	ServerKey     []byte                 `protobuf:"bytes,6,opt,name=server_key,json=serverKey,proto3" json:"server_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegComplete) Reset() {
	*x = RegComplete{}
	mi := &file_server_proto_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegComplete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegComplete) ProtoMessage() {}

func (x *RegComplete) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegComplete.ProtoReflect.Descriptor instead.
func (*RegComplete) Descriptor() ([]byte, []int) {
	return file_server_proto_api_proto_rawDescGZIP(), []int{3}
}

func (x *RegComplete) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RegComplete) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *RegComplete) GetSaltRoot() []byte {
	if x != nil {
		return x.SaltRoot
	}
	return nil
}

func (x *RegComplete) GetKdfParams() *KDFParams {
	if x != nil {
		return x.KdfParams
	}
	return nil
}

func (x *RegComplete) GetStoredKey() []byte {
	if x != nil {
		return x.StoredKey
	}
	return nil
}

func (x *RegComplete) GetServerKey() []byte {
	if x != nil {
		return x.ServerKey
	}
	return nil
}

type LoginStart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	ClientNonce   []byte                 `protobuf:"bytes,2,opt,name=client_nonce,json=clientNonce,proto3" json:"client_nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginStart) Reset() {
	*x = LoginStart{}
	mi := &file_server_proto_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginStart) ProtoMessage() {}

func (x *LoginStart) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginStart.ProtoReflect.Descriptor instead.
func (*LoginStart) Descriptor() ([]byte, []int) {
	return file_server_proto_api_proto_rawDescGZIP(), []int{4}
}

func (x *LoginStart) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *LoginStart) GetClientNonce() []byte {
	if x != nil {
		return x.ClientNonce
	}
	return nil
}

type LoginParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KdfParams     *KDFParams             `protobuf:"bytes,1,opt,name=kdf_params,json=kdfParams,proto3" json:"kdf_params,omitempty"`
	SaltRoot      []byte                 `protobuf:"bytes,2,opt,name=salt_root,json=saltRoot,proto3" json:"salt_root,omitempty"`
	ServerNonce   []byte                 `protobuf:"bytes,3,opt,name=server_nonce,json=serverNonce,proto3" json:"server_nonce,omitempty"`
	SessionId     string                 `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginParams) Reset() {
	*x = LoginParams{}
	mi := &file_server_proto_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginParams) ProtoMessage() {}

func (x *LoginParams) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginParams.ProtoReflect.Descriptor instead.
func (*LoginParams) Descriptor() ([]byte, []int) {
	return file_server_proto_api_proto_rawDescGZIP(), []int{5}
}

func (x *LoginParams) GetKdfParams() *KDFParams {
	if x != nil {
		return x.KdfParams
	}
	return nil
}

func (x *LoginParams) GetSaltRoot() []byte {
	if x != nil {
		return x.SaltRoot
	}
	return nil
}

func (x *LoginParams) GetServerNonce() []byte {
	if x != nil {
		return x.ServerNonce
	}
	return nil
}

func (x *LoginParams) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type LoginComplete struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Login         string                 `protobuf:"bytes,2,opt,name=login,proto3" json:"login,omitempty"`
	ClientNonce   []byte                 `protobuf:"bytes,3,opt,name=client_nonce,json=clientNonce,proto3" json:"client_nonce,omitempty"`
	ServerNonce   []byte                 `protobuf:"bytes,4,opt,name=server_nonce,json=serverNonce,proto3" json:"server_nonce,omitempty"`
	ClientProof   []byte                 `protobuf:"bytes,5,opt,name=client_proof,json=clientProof,proto3" json:"client_proof,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginComplete) Reset() {
	*x = LoginComplete{}
	mi := &file_server_proto_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginComplete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginComplete) ProtoMessage() {}

func (x *LoginComplete) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginComplete.ProtoReflect.Descriptor instead.
func (*LoginComplete) Descriptor() ([]byte, []int) {
	return file_server_proto_api_proto_rawDescGZIP(), []int{6}
}

func (x *LoginComplete) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *LoginComplete) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *LoginComplete) GetClientNonce() []byte {
	if x != nil {
		return x.ClientNonce
	}
	return nil
}

func (x *LoginComplete) GetServerNonce() []byte {
	if x != nil {
		return x.ServerNonce
	}
	return nil
}

func (x *LoginComplete) GetClientProof() []byte {
	if x != nil {
		return x.ClientProof
	}
	return nil
}

type SessionResult struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ServerSignature []byte                 `protobuf:"bytes,1,opt,name=server_signature,json=serverSignature,proto3" json:"server_signature,omitempty"`
	AccessToken     string                 `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken    string                 `protobuf:"bytes,3,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SessionResult) Reset() {
	*x = SessionResult{}
	mi := &file_server_proto_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionResult) ProtoMessage() {}

func (x *SessionResult) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionResult.ProtoReflect.Descriptor instead.
func (*SessionResult) Descriptor() ([]byte, []int) {
	return file_server_proto_api_proto_rawDescGZIP(), []int{7}
}

func (x *SessionResult) GetServerSignature() []byte {
	if x != nil {
		return x.ServerSignature
	}
	return nil
}

func (x *SessionResult) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *SessionResult) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type RefreshTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenRequest) Reset() {
	*x = RefreshTokenRequest{}
	mi := &file_server_proto_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenRequest) ProtoMessage() {}

func (x *RefreshTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenRequest.ProtoReflect.Descriptor instead.
func (*RefreshTokenRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_api_proto_rawDescGZIP(), []int{8}
}

func (x *RefreshTokenRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type RefreshTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenResponse) Reset() {
	*x = RefreshTokenResponse{}
	mi := &file_server_proto_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenResponse) ProtoMessage() {}

func (x *RefreshTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenResponse.ProtoReflect.Descriptor instead.
func (*RefreshTokenResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_api_proto_rawDescGZIP(), []int{9}
}

func (x *RefreshTokenResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *RefreshTokenResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type RevokeTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeTokenRequest) Reset() {
	*x = RevokeTokenRequest{}
	mi := &file_server_proto_api_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeTokenRequest) ProtoMessage() {}

func (x *RevokeTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_api_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeTokenRequest.ProtoReflect.Descriptor instead.
func (*RevokeTokenRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_api_proto_rawDescGZIP(), []int{10}
}

func (x *RevokeTokenRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

var File_server_proto_api_proto protoreflect.FileDescriptor

const file_server_proto_api_proto_rawDesc = "" +
	"\n" +
	"\x16server/proto/api.proto\x12\x03api\x1a\x1bgoogle/protobuf/empty.proto\"J\n" +
	"\tKDFParams\x12\x12\n" +
	"\x04time\x18\x01 \x01(\rR\x04time\x12\x17\n" +
	"\amem_kib\x18\x02 \x01(\rR\x06memKib\x12\x10\n" +
	"\x03par\x18\x03 \x01(\rR\x03par\" \n" +
	"\bRegStart\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\"v\n" +
	"\tRegParams\x12-\n" +
	"\n" +
	"kdf_params\x18\x01 \x01(\v2\x0e.api.KDFParamsR\tkdfParams\x12\x1b\n" +
	"\tsalt_root\x18\x02 \x01(\fR\bsaltRoot\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\"\xcc\x01\n" +
	"\vRegComplete\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05login\x18\x02 \x01(\tR\x05login\x12\x1b\n" +
	"\tsalt_root\x18\x03 \x01(\fR\bsaltRoot\x12-\n" +
	"\n" +
	"kdf_params\x18\x04 \x01(\v2\x0e.api.KDFParamsR\tkdfParams\x12\x1d\n" +
	"\n" +
	"stored_key\x18\x05 \x01(\fR\tstoredKey\x12\x1d\n" +
	"\n" +
	"server_key\x18\x06 \x01(\fR\tserverKey\"E\n" +
	"\n" +
	"LoginStart\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12!\n" +
	"\fclient_nonce\x18\x02 \x01(\fR\vclientNonce\"\x9b\x01\n" +
	"\vLoginParams\x12-\n" +
	"\n" +
	"kdf_params\x18\x01 \x01(\v2\x0e.api.KDFParamsR\tkdfParams\x12\x1b\n" +
	"\tsalt_root\x18\x02 \x01(\fR\bsaltRoot\x12!\n" +
	"\fserver_nonce\x18\x03 \x01(\fR\vserverNonce\x12\x1d\n" +
	"\n" +
	"session_id\x18\x04 \x01(\tR\tsessionId\"\xad\x01\n" +
	"\rLoginComplete\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05login\x18\x02 \x01(\tR\x05login\x12!\n" +
	"\fclient_nonce\x18\x03 \x01(\fR\vclientNonce\x12!\n" +
	"\fserver_nonce\x18\x04 \x01(\fR\vserverNonce\x12!\n" +
	"\fclient_proof\x18\x05 \x01(\fR\vclientProof\"\x82\x01\n" +
	"\rSessionResult\x12)\n" +
	"\x10server_signature\x18\x01 \x01(\fR\x0fserverSignature\x12!\n" +
	"\faccess_token\x18\x02 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x03 \x01(\tR\frefreshToken\":\n" +
	"\x13RefreshTokenRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"^\n" +
	"\x14RefreshTokenResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\"9\n" +
	"\x12RevokeTokenRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken2\xe1\x02\n" +
	"\x04Auth\x12-\n" +
	"\fGetRegParams\x12\r.api.RegStart\x1a\x0e.api.RegParams\x127\n" +
	"\vCompleteReg\x12\x10.api.RegComplete\x1a\x16.google.protobuf.Empty\x123\n" +
	"\x0eGetLoginParams\x12\x0f.api.LoginStart\x1a\x10.api.LoginParams\x127\n" +
	"\rCompleteLogin\x12\x12.api.LoginComplete\x1a\x12.api.SessionResult\x12C\n" +
	"\fRefreshToken\x12\x18.api.RefreshTokenRequest\x1a\x19.api.RefreshTokenResponse\x12>\n" +
	"\vRevokeToken\x12\x17.api.RevokeTokenRequest\x1a\x16.google.protobuf.EmptyB1Z/github.com/dtroode/gophkeeper-auth/server/protob\x06proto3"

var (
	file_server_proto_api_proto_rawDescOnce sync.Once
	file_server_proto_api_proto_rawDescData []byte
)

func file_server_proto_api_proto_rawDescGZIP() []byte {
	file_server_proto_api_proto_rawDescOnce.Do(func() {
		file_server_proto_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_server_proto_api_proto_rawDesc), len(file_server_proto_api_proto_rawDesc)))
	})
	return file_server_proto_api_proto_rawDescData
}

var file_server_proto_api_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_server_proto_api_proto_goTypes = []any{
	(*KDFParams)(nil),            // 0: api.KDFParams
	(*RegStart)(nil),             // 1: api.RegStart
	(*RegParams)(nil),            // 2: api.RegParams
	(*RegComplete)(nil),          // 3: api.RegComplete
	(*LoginStart)(nil),           // 4: api.LoginStart
	(*LoginParams)(nil),          // 5: api.LoginParams
	(*LoginComplete)(nil),        // 6: api.LoginComplete
	(*SessionResult)(nil),        // 7: api.SessionResult
	(*RefreshTokenRequest)(nil),  // 8: api.RefreshTokenRequest
	(*RefreshTokenResponse)(nil), // 9: api.RefreshTokenResponse
	(*RevokeTokenRequest)(nil),   // 10: api.RevokeTokenRequest
	(*emptypb.Empty)(nil),        // 11: google.protobuf.Empty
}
var file_server_proto_api_proto_depIdxs = []int32{
	0,  // 0: api.RegParams.kdf_params:type_name -> api.KDFParams
	0,  // 1: api.RegComplete.kdf_params:type_name -> api.KDFParams
	0,  // 2: api.LoginParams.kdf_params:type_name -> api.KDFParams
	1,  // 3: api.Auth.GetRegParams:input_type -> api.RegStart
	3,  // 4: api.Auth.CompleteReg:input_type -> api.RegComplete
	4,  // 5: api.Auth.GetLoginParams:input_type -> api.LoginStart
	6,  // 6: api.Auth.CompleteLogin:input_type -> api.LoginComplete
	8,  // 7: api.Auth.RefreshToken:input_type -> api.RefreshTokenRequest
	10, // 8: api.Auth.RevokeToken:input_type -> api.RevokeTokenRequest
	2,  // 9: api.Auth.GetRegParams:output_type -> api.RegParams
	11, // 10: api.Auth.CompleteReg:output_type -> google.protobuf.Empty
	5,  // 11: api.Auth.GetLoginParams:output_type -> api.LoginParams
	7,  // 12: api.Auth.CompleteLogin:output_type -> api.SessionResult
	9,  // 13: api.Auth.RefreshToken:output_type -> api.RefreshTokenResponse
	11, // 14: api.Auth.RevokeToken:output_type -> google.protobuf.Empty
	9,  // [9:15] is the sub-list for method output_type
	3,  // [3:9] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_server_proto_api_proto_init() }
func file_server_proto_api_proto_init() {
	if File_server_proto_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_server_proto_api_proto_rawDesc), len(file_server_proto_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_server_proto_api_proto_goTypes,
		DependencyIndexes: file_server_proto_api_proto_depIdxs,
		MessageInfos:      file_server_proto_api_proto_msgTypes,
	}.Build()
	File_server_proto_api_proto = out.File
	file_server_proto_api_proto_goTypes = nil
	file_server_proto_api_proto_depIdxs = nil
}
